/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pznuzutnircobizcdowf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnV6dXRuaXJjb2JpemNkb3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjc3NDAsImV4cCI6MjA3MTYwMzc0MH0.S5k3yuYAv17EAnn3-DFdxThrvL-HGcemKq-qpsjetq4"